spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.113/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.1.113
    port: 6379
server:
  context-path: /sell
debug: true
wechat:
  myAppId: wxe42c3558c8fc34d9
  myAppSecret: c53c3273537b0658db67d66b11d44ad2
  mchId: 14090146202
  mchKey: c976503d34ca432c601361f969fd8d85
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://sell.natapp4.cc/sell/pay/notify
  templateId:
     orderStatus : Yq2_iXX07vZMYCnwZHRRirifFetqeXgOZFzyR0VR4ZY
projectUrl:
  wechatMpAuthorize: http://v5gmgr.s1.natapp.cc
  sell: http://v5gmgr.s1.natapp.cc
logging:
  level:
    com.yan.sell.dataobject.mapper: trace
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #classpath记录为resources路径下
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  level:
#    com.yanshizhi.sell.SellApplicationTests: debugks
